services:
  - type: web
    name: gode-million-api
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGO_URI
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://gode-million-web.onrender.com

  - type: static
    name: gode-million-web
    runtime: static
    plan: free
    region: frankfurt
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://gode-million-api.onrender.com/api
